"""Create execution_log table

Revision ID: 551111690c71
Revises: 
Create Date: 2024-05-30 17:54:41.373752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '551111690c71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wc_farms_sensors')
    op.drop_table('wc_farms_zones')
    op.drop_table('wc_farms_irrigation')
    op.drop_table('wc_farms_nodes')
    op.drop_table('wc_farms_hydraulics')
    op.drop_table('execution_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='execution_log_pkey')
    )
    op.create_table('wc_farms_hydraulics',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('farmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nodeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parentids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zoneids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sensor_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sensor_measureid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wc_farms_hydraulics_pkey')
    )
    op.create_table('wc_farms_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('farmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nodetype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wc_farms_nodes_pkey')
    )
    op.create_table('wc_farms_irrigation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inittime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('irrigationtype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pumpsystemid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pumpids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zoneid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('senttonetwork', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scheduledtype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hydraulics', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('groupingname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('volume_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitation_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('theoreticalflow_m3_h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wc_farms_irrigation_pkey')
    )
    op.create_table('wc_farms_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('farmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pumpsystemid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('theoreticalflowm3h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('humidityretention', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticalpoint1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticalpoint2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticalpoint3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticalpoint4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('soilmode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crops', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pumpids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('predefinedpumps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('irrigation_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irrigation_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irrigation_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irrigation_std', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('southwest_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('southwest_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('northeast_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('northeast_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wc_farms_zones_pkey')
    )
    op.create_table('wc_farms_sensors',
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('farmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zoneid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lastdata', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lastdatadate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('monitoringtime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nodeid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sensortype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name='sensors_pkey')
    )
    # ### end Alembic commands ###
