"""Initial migration

Revision ID: c32f85e7fd12
Revises: 
Create Date: 2024-05-17 18:29:18.326023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32f85e7fd12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wc_farms_zones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wc_farms_zones',
    sa.Column('id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.TEXT(), nullable=True),
    sa.Column('longitude', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('farmId', sa.BIGINT(), nullable=True),
    sa.Column('pumpSystemId', sa.FLOAT(), nullable=True),
    sa.Column('kc', sa.BIGINT(), nullable=True),
    sa.Column('theoreticalFlow m3/h', sa.FLOAT(), nullable=True),
    sa.Column('efficiency', sa.TEXT(), nullable=True),
    sa.Column('humidityRetention', sa.TEXT(), nullable=True),
    sa.Column('max', sa.TEXT(), nullable=True),
    sa.Column('min', sa.TEXT(), nullable=True),
    sa.Column('criticalPoint1', sa.TEXT(), nullable=True),
    sa.Column('criticalPoint2', sa.TEXT(), nullable=True),
    sa.Column('criticalPoint3', sa.TEXT(), nullable=True),
    sa.Column('criticalPoint4', sa.TEXT(), nullable=True),
    sa.Column('soilMode', sa.TEXT(), nullable=True),
    sa.Column('crops', sa.TEXT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('BFPressureId', sa.TEXT(), nullable=True),
    sa.Column('onlyMonitoring', sa.BOOLEAN(), nullable=True),
    sa.Column('area m2', sa.FLOAT(), nullable=True),
    sa.Column('allowPumpSelection', sa.BOOLEAN(), nullable=True),
    sa.Column('pumpIds', sa.TEXT(), nullable=True),
    sa.Column('predefinedPumps', sa.TEXT(), nullable=True),
    sa.Column('irrigation_max', sa.FLOAT(), nullable=True),
    sa.Column('irrigation_min', sa.FLOAT(), nullable=True),
    sa.Column('irrigation_avg', sa.FLOAT(), nullable=True),
    sa.Column('irrigation_std', sa.FLOAT(), nullable=True),
    sa.Column('southWest_lng', sa.FLOAT(), nullable=True),
    sa.Column('southWest_lat', sa.FLOAT(), nullable=True),
    sa.Column('northEast_lng', sa.FLOAT(), nullable=True),
    sa.Column('northEast_lat', sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
