name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Ensure deployment directory exists
      run: ssh -o StrictHostKeyChecking=no ubuntu@18.117.28.235 'mkdir -p /home/ubuntu/integracionwiseconn'

    - name: Copy files via SCP
      run: scp -r -o StrictHostKeyChecking=no ./* ubuntu@18.117.28.235:/home/ubuntu/integracionwiseconn

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.117.28.235 << 'EOF'
        cd /home/ubuntu/integracionwiseconn
        sudo pip3 install -r requirements.txt
        exit
        EOF

    - name: SSH and restart service
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.117.28.235 << 'EOF'
        cd /home/ubuntu/integracionwiseconn
        sudo systemctl restart integracionwiseconn.service
        exit
        EOF
